/**
 *
 * $Id$
 */
package nrp.model.nrp.validation;

import nrp.model.nrp.RequirementRealisation;
import nrp.model.nrp.Valuation;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link nrp.model.nrp.Requirement}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface RequirementValidator {
	boolean validate();

	boolean validateName(String value);

	boolean validateValuations(EList<Valuation> value);

	boolean validateRealisations(EList<RequirementRealisation> value);

	boolean validateCombines(EList<Valuation> value);
}
