/**
 *
 * $Id$
 */
package nrp.model.nrp.validation;

import nrp.model.nrp.CostType;

/**
 * A sample validator interface for {@link nrp.model.nrp.Cost}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface CostValidator {
	boolean validate();

	boolean validateType(CostType value);

	boolean validateAmount(double value);
}
