/**
 *
 * $Id$
 */
package nrp.model.nrp.validation;

import nrp.model.nrp.Customer;
import nrp.model.nrp.Requirement;
import nrp.model.nrp.SoftwareArtifact;
import nrp.model.nrp.Solution;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link nrp.model.nrp.NRP}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface NRPValidator {
	boolean validate();

	boolean validateCustomers(EList<Customer> value);

	boolean validateAvailableArtifacts(EList<SoftwareArtifact> value);

	boolean validateRequirements(EList<Requirement> value);

	boolean validateSolutions(Solution value);

	boolean validateSolutions(EList<Solution> value);
}
