/**
 *
 * $Id$
 */
package nrp.model.nrp.validation;

import nrp.model.nrp.Cost;
import nrp.model.nrp.RequirementRealisation;
import nrp.model.nrp.SoftwareArtifact;
import nrp.model.nrp.Solution;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link nrp.model.nrp.SoftwareArtifact}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface SoftwareArtifactValidator {
	boolean validate();

	boolean validateName(String value);

	boolean validateRequires(EList<SoftwareArtifact> value);

	boolean validateCosts(EList<Cost> value);

	boolean validateContributesTo(EList<RequirementRealisation> value);

	boolean validateSolutions(EList<Solution> value);
}
