/**
 *
 * $Id$
 */
package nrp.model.nrp.validation;

import nrp.model.nrp.Customer;
import nrp.model.nrp.Requirement;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link nrp.model.nrp.Valuation}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ValuationValidator {
	boolean validate();

	boolean validateRequirement(Requirement value);

	boolean validateValue(double value);

	boolean validateAssignedBy(EList<Customer> value);

	boolean validateContributesTo(EList<Requirement> value);
}
